<div class="background-container" style="background-image: url('/themes/{{ $shop_theme }}/img/home-banner.jpg')">
	<div class="container">
		<div class="heading-container">LACK OF FOCUS</div>
		<div class="subheading-container">THE ARSENIC OF THE WOMAN ENTREPRENEUR</div>
		<div class="sender-container">Story by Kathy McShaine</div>
		<div class="date-container">12/01/2017</div>
		<div class="content-container">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus obcaecati, cum. Ea ipsa quisquam, ducimus, harum adipisci blanditiis dolor deserunt, odio reprehenderit ullam consequatur magni deleniti suscipit ad praesentium repellendus! Similique quis maiores praesentium ratione illum alias fugit, ipsum officiis vero sit, repellendus quisquam excepturi quam dolorum suscipit. Itaque saepe optio dicta blanditiis deserunt atque necessitatibus sit quia unde natus mollitia recusandae ipsam cumque vitae earum commodi dolor labore deleniti et doloribus voluptate, dolorem fuga sed beatae nisi. Necessitatibus, aspernatur reiciendis officia. Recusandae pariatur suscipit culpa alias reiciendis esse, dolorum cumque! Animi, architecto. Vero beatae voluptate et quod necessitatibus molestiae eius accusamus esse pariatur soluta, officia suscipit! Impedit at pariatur perferendis dolorem ipsum hic maiores aperiam vel eos laborum molestias esse atque minus voluptatibus quam, excepturi incidunt ipsa iure illo tempore tenetur dignissimos! Consequuntur a provident quidem possimus veniam eius molestias, rem quia rerum nulla itaque atque dicta quo culpa dolorum, facere, minima aperiam. Voluptates delectus in voluptatum facilis modi cum, quod magnam repudiandae nisi tempore reprehenderit, pariatur, voluptas. Fugiat incidunt, blanditiis eos exercitationem amet qui commodi accusamus molestias sapiente similique, ipsa ipsam atque, quam. Ratione nam qui praesentium tenetur est autem, eaque laboriosam dolorem! Quod quam atque beatae, laudantium est expedita culpa fugit repellendus et, ipsa iure aut, id inventore iste molestiae error cum nam vel. Quod quas odio atque fugiat  Repellat alias fugit laborum ea perferendis eligendi dolorum vero voluptatem vel ipsum? Rem, iure.</div>
		<div class="content-container">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam harum expedita itaque nesciunt eveniet nostrum amet magni eaque provident incidunt nemo dolor, maiores quae, iure nihil illo. Exercitationem suscipit labore molestiae repellat placeat fuga voluptate saepe autem neque porro, officiis in at rem quas quasi, velit dolore facilis aspernatur est quae reprehenderit adipisci voluptates culpa. Quam fugiat fugit ratione debitis quidem saepe deserunt, doloribus aliquid inventore natus cupiditate voluptatem, voluptate odio reiciendis molestiae libero assumenda quisquam quibusdam quasi magni illo eaque ullam sunt. Maxime accusantium maiores nobis molestiae sequi fugit, placeat vero voluptatibus? Labore neque, voluptatem in accusamus nulla voluptates. Deleniti odit, ut, vitae quisquam dolore, ad placeat debitis nisi labore, dolorum explicabo itaque commodi sapiente tempora molestias eligendi fugit sit maxime? Recusandae voluptas sequi, est dolorum atque tempore suscipit necessitatibus, vero repellendus porro ullam pariatur quo laudantium repudiandae a hic itaque, architecto at! Ratione, illum, beatae, placeat similique necessitatibus dolorem voluptate earum, blanditiis voluptatum quod nesciunt. Sapiente et totam nihil beatae aut deserunt quidem voluptatum veritatis cumque delectus expedita rem deleniti eaque illo, dolorem suscipit repudiandae, distinctio illum? Repellat assumenda amet quo nisi, itaque sit deleniti magnam quaerat enim soluta accusamus recusandae pariatur repudiandae non optio sequi, fugit adipisci.</div>
	</div>
</div>

<link rel="stylesheet" type="text/css" href="/themes/{{ $shop_theme }}/css/press_email.css">
